### ISSUE TITLE
Have you talked to HotJar about this problem?

### ISSUE THREAD

**Issue by bikegriffith** [Trott/hotjar-xhr-prototype-issue#1]
We saw it on a customer site.  The problem is that they pass along the 3rd argument to `open` (the optional `async` parameter) through `xo.call`.  When the user doesn't supply a value, it calls `open(l, j, undefined, ...)` … they need to set `m` to `true` if it really is `undefined` to not confuse the browser into thinking the user passed a falsey value

**Comment by Trott** [comment]
I'm pretty sure I sent this bug demo to them but that was almost a year ago. I don't remember what they said. It's possible I just needed to update my hotjar snippet. I don't remember. We're not using hotjar anymore so...uh... `¯\_(ツ)_/¯`
